# Generated by Django 4.2.5 on 2023-09-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='final_date',
            field=models.CharField(default='21/09/2023', max_length=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='start_date',
            field=models.CharField(default='21/09/2023', max_length=10),
        ),
    ]
