# Generated by Django 4.2.5 on 2023-09-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_final_date_todo_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='final_date',
            new_name='end_date',
        ),
    ]
