# Generated by Django 4.1.9 on 2023-09-25 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_final_date_todo_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.CharField(default='25/09/2023', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.CharField(default=datetime.datetime(2023, 9, 25, 19, 3, 33, 765042, tzinfo=datetime.timezone.utc), max_length=10),
        ),
    ]
