# Generated by Django 4.1.9 on 2023-09-25 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.CharField(default=datetime.datetime(2023, 9, 25, 19, 7, 4, 461475, tzinfo=datetime.timezone.utc), max_length=5000),
        ),
    ]
