# Generated by Django 4.1.9 on 2023-09-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_todo_end_date_alter_todo_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.CharField(default='25/09/2023 - 19:11', max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.CharField(default='25/09/2023 - 19:11', max_length=20),
        ),
    ]
