# Generated by Django 4.1.9 on 2023-09-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_todo_end_date_alter_todo_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.CharField(default='26/09/2023 - 21:26', max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.CharField(default='26/09/2023 - 21:26', max_length=50),
        ),
    ]
